### ISSUE TITLE
H5容器里面的H5_PAGE_ERROR不回调

### ISSUE THREAD

**Issue by wu19910708** [alipay/mpaas-demo#1]
当H5加载的时候，，如果加载错误只会回调H5_PAGE_FINISHED这个Action并不会回调H5_PAGE_ERROR，我现在想处理H5_PAGE_ERROR，用原生的错误展示界面

**Comment by SpinyTech** [comment]
您可以实现 H5ErrorPageView，在 errorPageCallback 启动原生页面。

具体可参考
https://tech.antfin.com/docs/2/126953#h2--h5-2
