### ISSUE TITLE
生成amr包报格式错误

### ISSUE THREAD

**Issue by apigonthsky** [alipay/mpaas-demo#10]
请问我按照贵司的流程指导https://tech.antfin.com/docs/2/85627
进行生成amr包（一般资源包），报“打包失败，请检查上传包格式”。这个问题如何处理？
这个有什么需要注意的地方？

**Comment by glcrazier** [comment]
提供下appid以及上传包的目录结构

**Comment by apigonthsky** [comment]
appid: 20190830
结构： 20190830/www/

**Comment by apigonthsky** [comment]
错误：
![image](https://user-images.githubusercontent.com/9649573/64012927-42803a00-cb51-11e9-984d-09927e75442d.png)
结构：
![image](https://user-images.githubusercontent.com/9649573/64013013-7eb39a80-cb51-11e9-8966-79c7a144c3f9.png)

**Comment by glcrazier** [comment]
压缩包内的文件名不允许中文

**Comment by apigonthsky** [comment]
恩 谢谢，已经打包成功。
