### ISSUE TITLE
离线包更新失败

### ISSUE THREAD

**Issue by apigonthsky** [alipay/mpaas-demo#11]
错误提示：
![image](https://user-images.githubusercontent.com/9649573/64098755-4226af80-cd9a-11e9-9aed-0643bd916a2f.png)
![image](https://user-images.githubusercontent.com/9649573/64098775-4bb01780-cd9a-11e9-8120-ebbcae06d07e.png)
![image](https://user-images.githubusercontent.com/9649573/64098788-510d6200-cd9a-11e9-878a-82f4e4af7fce.png)

是不是跟验签公钥有关，喔按照 指导流程来的https://tech.antfin.com/docs/2/130807
并没有添加验签，所以我怀疑是验签相关的问题。

**Comment by glcrazier** [comment]
没有配置好无线保镖图片，请在控制台上传apk并下载配置文件放到工程中重新编译

**Comment by apigonthsky** [comment]
![image](https://user-images.githubusercontent.com/9649573/64141153-a0569f80-ce39-11e9-9f73-85eb02921ae2.png)
![image](https://user-images.githubusercontent.com/9649573/64141212-c8460300-ce39-11e9-8b11-5bd7258b58a8.png)
![image](https://user-images.githubusercontent.com/9649573/64141231-d09e3e00-ce39-11e9-9502-92ad0566d57b.png)

**Comment by apigonthsky** [comment]
已经解决了。
使用mPaas方案的H5组件时，我更新离线包本地报错为：607  
根据错误码：https://tech.antfin.com/docs/2/70196 所以推测为无线保镖图片有误，才有这么个申请。
解决方案为签名重新生成来对应配置，估计是我们本地的签名使用时不匹配导致的，也算是签名安全问题。
总之，很感谢你们的支持。
