### ISSUE TITLE
离线包离线状态下不可用或加载不出来

### ISSUE THREAD

**Issue by apigonthsky** [alipay/mpaas-demo#13]
问题已经被解决了。
这个是阿里的安全方案设计，主要就是为了做验签。
无论是预置还是更新后的离线包都默认会做验签。
验签开关方法：https://tech.antfin.com/docs/2/118673
效果：关了验签后，离线包加载速度有了较大的提升，在断网情况下也可以使用了。

**Comment by SpinyTech** [comment]
👍
