### ISSUE TITLE
UCWebview如何设置横竖屏显示

### ISSUE THREAD

**Issue by wenchaoweng** [alipay/mpaas-demo#15]
原生Webview可以随着手机转成横屏而显示横屏, 但UCWebview好像默认就是竖屏, 如何设置成横屏显示?

**Comment by SpinyTech** [comment]
在你的 manifest 中加入如下代码即可

<activity
            android:name="com.alipay.mobile.nebulacore.ui.H5Activity"
            android:configChanges="orientation|keyboardHidden|navigation|screenSize|smallestScreenSize|screenLayout"
            android:exported="false"
            android:hardwareAccelerated="true"
            android:screenOrientation="landscape"
            android:windowSoftInputMode="adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
