### ISSUE TITLE
window 下载demo运行出错：java.io.IOException: Unable to delete file

### ISSUE THREAD

**Issue by apigonthsky** [alipay/mpaas-demo#16]
* What went wrong:
java.io.IOException: Unable to delete file: D:\***\Desktop\mPass\mpaas-demo\mpaas-demo\mpaas_nebula_demo\mpaas_nebula_demo_android\app\build\intermediates\transforms\stripDebugSymbol\debug\0\lib\armeabi\libandroid-phone-thirdparty-utdid.so
> Unable to delete file: D:\***\Desktop\mPass\mpaas-demo\mpaas-demo\mpaas_nebula_demo\mpaas_nebula_demo_android\app\build\intermediates\transforms\stripDebugSymbol\debug\0\lib\armeabi\libandroid-phone-thirdparty-utdid.so
![image](https://user-images.githubusercontent.com/9649573/64326518-b3fe3380-cffc-11e9-9e47-9e3f171c4299.png)
出错版本：classpath 'com.alipay.android:android-gradle-plugin:3.0.0.7.25'
修改为classpath 'com.alipay.android:android-gradle-plugin:3.0.0.8.0'则不报该问题，可见更新新版本即可解决。

**Comment by SpinyTech** [comment]
出错版本：classpath 'com.alipay.android:android-gradle-plugin:3.0.0.7.25'
修改为classpath 'com.alipay.android:android-gradle-plugin:3.0.0.8.0'则不报该问题，可见更新新版本即可解决。
