### ISSUE TITLE
在mpass发布的小程序，iOS 加载小程序都必须将配置信息写进NAMApplist.plist吗？

### ISSUE THREAD

**Issue by farewell17** [alipay/mpaas-demo#19]

**Comment by vivi23vivi** [comment]
小程序包不是必须要预置在客户端，您可以直接在控制台上传小程序包后，创建发布任务，然后再客户端调用加载小程序包的接口，就可以打开对应的小程序了，对应的文档请参考https://tech.antfin.com/docs/2/67650。

预置小程序只是一种辅助手段，可以直接加载本地的小程序包而不用进行下载包的操作，从而摆脱网络对小程序包加载的限制，一般适用于在首页或重要且需要实时加载的业务场景。其他情况建议不要预置，避免客户端包大小过大


实现预置小程序包，您需要完成以下步骤
1、在控制台上传您开发完成的小程序包（主要是完成打包的任务），参考文档https://tech.antfin.com/docs/2/67650
2、在控制台下载生成的小程序amr包和对应的h5_json文件
![image](https://user-images.githubusercontent.com/13690895/64510911-b8389280-d315-11e9-8435-9fdc749e20c9.png)

3、将下载的小程序amr包和h5_json包信息文件预置在您自定义的小程序包路径下
说明：可以直接将h5_json.json文件存在对应路径，也可以将h5_json.json文件中的信息填写到NAMApplist.plist，两种方式2选1即可
![image](https://user-images.githubusercontent.com/13690895/64511320-a4416080-d316-11e9-88f2-6b713dcd291a.png)

**Comment by farewell17** [comment]
> 小程序包不是必须要预置在客户端，您可以直接在控制台上传小程序包后，创建发布任务，然后再客户端调用加载小程序包的接口，就可以打开对应的小程序了，对应的文档请参考[https://tech.antfin.com/docs/2/67650。](https://tech.antfin.com/docs/2/67650%E3%80%82)
> 
> 预置小程序只是一种辅助手段，可以直接加载本地的小程序包而不用进行下载包的操作，从而摆脱网络对小程序包加载的限制，一般适用于在首页或重要且需要实时加载的业务场景。其他情况建议不要预置，避免客户端包大小过大
> 
> 实现预置小程序包，您需要完成以下步骤
> 1、在控制台上传您开发完成的小程序包（主要是完成打包的任务），参考文档https://tech.antfin.com/docs/2/67650
> 2、在控制台下载生成的小程序amr包和对应的h5_json文件
> ![image](https://user-images.githubusercontent.com/13690895/64510911-b8389280-d315-11e9-8435-9fdc749e20c9.png)
> 
> 3、将下载的小程序amr包和h5_json包信息文件预置在您自定义的小程序包路径下
> 说明：可以直接将h5_json.json文件存在对应路径，也可以将h5_json.json文件中的信息填写到NAMApplist.plist，两种方式2选1即可
> ![image](https://user-images.githubusercontent.com/13690895/64511320-a4416080-d316-11e9-88f2-6b713dcd291a.png)

**Comment by farewell17** [comment]
客户端直接调用加载小程序包的接口，打开小程序，这个是会在后台下载，这样在展示的小程序的内容时会白屏很长时间。而且如果我想通过后台动态配置多个小程序，然后去加载其中的某一个，需要把发布的小程序h5_json写进本地保存的沙河路径里面，然后从里面读，这样思路有没有问题呀

**Comment by vivi23vivi** [comment]
1、控制台支持同时发布多个小程序，您只需在需要加载的地方，打开对应小程序id就可以
2、h5_json文件只有在是需要在本地预置离线包或者小程序的时候，才需要在工程中配置。如果您为了减少去拉取包儿出现等待的情况，可以将需要的离线包或小程序预置。若预置的有多个包，需要把相关的包信息，写到同一个h5_json文件中。

**Comment by farewell17** [comment]
好的，多谢
