### ISSUE TITLE
自定义JSAPI 调取摄像头拍完照后，插件不能继承H5Acitivity,无法写onActivityResult 回调

### ISSUE THREAD

**Issue by huangjinlangzi** [alipay/mpaas-demo#2]

**Comment by SpinyTech** [comment]
目前您可以使用一个透明 activity 来启动相机，并接收返回参数，然后再通过广播（或其他手段通知您的jsapi）

由于我们在 H5Activity 中做了不少的工作，所以暂时不能开发继承 H5Activity，不过这是一个非常好的 issue，后续我们看是否可以开发一些 H5Activity 的回调来解决这个问题。

**Comment by glcrazier** [comment]
@huangjinlangzi https://tech.antfin.com/docs/2/126953#h2-h5plugin-activity-result1 参考这个实现回调
