### ISSUE TITLE
iOS升级到10.1.60后报错如下

### ISSUE THREAD

**Issue by fyn212319** [alipay/mpaas-demo#22]
Showing Recent Messages
:-1: Undefined symbol: _MPMoviePlayerThumbnailImageKey

:-1: Undefined symbol: _MPMoviePlayerPlaybackStateDidChangeNotification

:-1: Undefined symbol: _OBJC_CLASS_$_MPRemoteCommandCenter

:-1: Undefined symbol: _OBJC_CLASS_$_MPNowPlayingInfoCenter

:-1: Undefined symbol: _MPMoviePlayerThumbnailImageRequestDidFinishNotification

:-1: Undefined symbol: _MPMediaItemPropertyArtwork

:-1: Undefined symbol: _MPMediaItemPropertyTitle

:-1: Undefined symbol: _MPMediaItemPropertyArtist

:-1: Undefined symbol: _MPMediaItemPropertyAlbumTitle

:-1: Undefined symbol: _OBJC_CLASS_$_MPVolumeView

:-1: Undefined symbol: _OBJC_CLASS_$_MPMoviePlayerViewController

:-1: Undefined symbol: _OBJC_CLASS_$_MPMediaItemArtwork

:-1: Undefined symbol: _MPNowPlayingInfoPropertyElapsedPlaybackTime

:-1: Undefined symbol: _OBJC_CLASS_$_MPMusicPlayerController

:-1: Undefined symbol: _MPMediaItemPropertyPlaybackDuration

:-1: Undefined symbol: _MPNowPlayingInfoPropertyPlaybackRate

**Comment by vivi23vivi** [comment]
请在 Build Phease 中添加系统库 MediaPlayer
![image](https://user-images.githubusercontent.com/13690895/64688430-e9a09200-d4be-11e9-8252-3c284645fb4a.png)
