### ISSUE TITLE
H5离线包 中的部分资源(mp3/m4)无法访问使用，js、css可以。

### ISSUE THREAD

**Issue by apigonthsky** [alipay/mpaas-demo#24]
资源路径：
![image](https://user-images.githubusercontent.com/9649573/64760361-29718300-d56c-11e9-9dac-4df1353408fe.png)
本地资源:
![image](https://user-images.githubusercontent.com/9649573/64760376-342c1800-d56c-11e9-83e9-61fc3a34e2a7.png)
js 使用正常：
![image](https://user-images.githubusercontent.com/9649573/64760385-3bebbc80-d56c-11e9-8ab2-8ffdf35dcb50.png)

**Comment by SpinyTech** [comment]
目前UC和容器的策略，无法访问离线包内的相对路径的多媒体文件

解决方案：
1. 使用base64转码后进行播放
2. 改用在线资源方式
