### ISSUE TITLE
android H5容器如何设置WebViewClient和WebChromeClient?

### ISSUE THREAD

**Issue by wu19910708** [alipay/mpaas-demo#32]
我们项目现在需要单独写一套自己的JSBridge，所以会涉及到JS注入的时机问题，然后APWebView如何转成android webkit的WebView

**Comment by SpinyTech** [comment]
1. 注册自定义JSAPI插件，监听 CommonEvents.H5_PAGE_START，在 handleEvent 中，拿到 h5page 实例，通过调用 h5page.getWebView().setWebViewClient 和 setWebChromeClient 来完成设置，注意 设置的内容要继承 APWebViewClient 和 APWebChromeClient，和 google 原生的接口是一致的。
