### ISSUE TITLE
android 不预置h5，直接下载离线包

### ISSUE THREAD

**Issue by wu19910708** [alipay/mpaas-demo#4]
android 不预置h5，直接下载离线包，怎么应该怎么实现呢？

**Comment by glcrazier** [comment]
上传离线包到MDS，使用MPNebula.startApp方法即可

**Comment by wu19910708** [comment]
我现在h5容器没有用MPnebula.startApp()，，而是直接用的内嵌形式的
h5Page = h5Service.createPage(this, bundle);
            h5Page.getPluginManager().register(new NativeLoadingPlugin());
            FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(
                    AUFrameLayout.LayoutParams.MATCH_PARENT, AUFrameLayout.LayoutParams.WRAP_CONTENT);

            mContainer.addView(h5Page.getContentView(), lp);

这种情况应该怎么解决啊？

**Comment by SpinyTech** [comment]
> 我现在h5容器没有用MPnebula.startApp()，，而是直接用的内嵌形式的
> h5Page = h5Service.createPage(this, bundle);
> h5Page.getPluginManager().register(new NativeLoadingPlugin());
> FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(
> AUFrameLayout.LayoutParams.MATCH_PARENT, AUFrameLayout.LayoutParams.WRAP_CONTENT);
> 
> ```
>         mContainer.addView(h5Page.getContentView(), lp);
> ```
> 
> 这种情况应该怎么解决啊？

MPNebula.updateAll
