### ISSUE TITLE
如何对UC浏览器内核进行设置，比如禁用手势，禁止缩放等等

### ISSUE THREAD

**Issue by huangjinlangzi** [alipay/mpaas-demo#5]

**Comment by SpinyTech** [comment]
通过自定义 jsapi，拿到 H5Page，在H5Page中可以通过 getWebview 拿到 APWebview，然后通过 getSettings 拿到 APWebSettings，这里的 APWebSettings 和 Android WebSettings 接口一致，就可以按照原生方式禁止了。
