### ISSUE TITLE
小程序-开发调试过于麻烦

### ISSUE THREAD

**Issue by caoshining** [alipay/mpaas-demo#9]
![image](https://user-images.githubusercontent.com/19256823/63934071-1ac79e00-ca8d-11e9-922b-3cdb15af74c4.png)
![image](https://user-images.githubusercontent.com/19256823/63934103-2b781400-ca8d-11e9-9cd3-01ccbc8dae85.png)
可否直接类似app扫码之后直接进入调试。

**Comment by SpinyTech** [comment]
小程序调试功能正在内测中，后续会放出来，直接扫码打开

**Comment by glcrazier** [comment]
@caoshining 产品上设计是这样的，因为mpaas不只是有你一个用户，因此需要区分用户，所以得有白名单。麻烦再读下文档
